config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "customers#index"
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user

  # Instance Method
  def full_name
    #"#{self.first_name} #{self.last_name}"
    customer = Customer.find_by_sql(["
        SELECT 
        first_name, last_name 
        from customers AS c
        WHERE c.id = ?
      ", self.id]).first
      "#{customer.first_name} #{customer.last_name}"
  end

  # Model Method
  # Select all customer records for user
  def self.all_customers(user_id)
    Customer.find_by_sql("
      SELECT *
      FROM customers AS c
      WHERE c.user_id = #{user_id}
    ")
  end

  # Select a single customer for user
  def self.single_customer(user_id, customer_id)
    Customer.find_by_sql(["
        SELECT * 
        FROM customers AS c
        WHERE c.user_id = ?
        AND c.id = ?
      ", user_id, customer_id]).first
  end

  # Create a single customer
  def self.create_customer(params, user_id)
    Customer.find_by_sql(["
        INSERT INTO customers (first_name, last_name, email, phone, user_id, created_at, updated_at)
        VALUES (:first, :last, :email, :phone, :user_id, :created_at, :updated_at)
      ", {
        first: params[:first_name],
        last: params[:last_name],
        email: params[:email],
        phone: params[:phone],
        user_id: user_id,
        created_at: DateTime.now,
        updated_at: DateTime.now
      }])
  end

  # Update a single customer
  def self.update_customer(params, customer_id, user_id)
    Customer.find_by_sql(["
        UPDATE customers AS c
        SET first_name = ?, last_name = ?, email = ?, phone = ?, updated_at = ?
        WHERE c.id = ? AND c.user_id = ?
      ", params[:first_name], params[:last_name], params[:email], params[:phone], DateTime.now, customer_id, user_id])
  end

  # Delete a single customer
  def self.delete_customer(user_id, customer_id)
    Customer.find_by_sql(["
        DELETE FROM customers AS c
        WHERE c.user_id = ? AND c.id = ?
      ", user_id, customer_id])
  end
end



# IF USER ID IS A STRING OR USER NAME IS IN STRING FORMAT, YOU HAVE TO PASS IT IN AS FOLLOWS
# # Model Method
# def self.all_customers(user_id)
#   Customer.find_by_sql(["
#       SELECT *
#       FROM customers AS c
#       WHERE c.user_id = ?
#     ", user_id])
# end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all_customers(current_user.id)
  end

  def show
  end

  def new
    @customer = current_user.customers.new
  end

  def create
    Customer.create_customer(customer_params, current_user.id)
    redirect_to customers_path
  end

  def edit
  end

  def update
    Customer.update_customer(customer_params, @customer.id, current_user.id)
    redirect_to @customer
  end

  def destroy
    Customer.delete_customer(current_user.id, @customer)
    redirect_to customers_path
  end

  private

  def set_customer
    @customer = Customer.single_customer(current_user.id, params[:id])
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :email, :phone )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: @customer, local: true, class: "ui form") do |f| %>
    <div class="field">
        <%= f.label :first_name%>
        <%= f.text_field :first_name, class: "input"%>
    </div>
    <div class="field">
        <%= f.label :last_name%>
        <%= f.text_field :last_name, class: "input" %>
    </div>
    <div class="field">
        <%= f.label :email%>
        <%= f.email_field :email, class: "input" %>
    </div>
    <div class="field">
        <%= f.label :phone%>
        <%= f.phone_field :phone, class: "input" %>
    </div>
    <%= f.submit nil, class:"ui button green"%>
<% end %>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render "customers/form" %>

app/views/customers/index.html.erb
<h1>All Customers for <%= current_user.email %></h1>

<table class="ui table striped padded selectable">
<thead>
    <th>View</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Edit</th>
    <th>Remove</th>
</thead>
<tbody>
    <% @customers.each do |c| %>
        <tr>
            <td><%= link_to 'View', customer_path(c), class: "ui button blue" %></td>
            <td><%= c.first_name %></td>
            <td><%= c.last_name %></td>
            <td><%= c.email %></td>
            <td><%= c.phone %></td>
            <td><%= link_to 'Edit', edit_customer_path(c), class: "ui button orange"%></td>
            <td><%= button_to 'Remove', customer_path(c), method: :delete, class:"ui button red"%></td>
        </tr>
    <% end %>
</tbody>
</table>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render "customers/form" %>

app/views/customers/show.html.erb
<h1><%= @customer.full_name %></h1>


<table class="ui definition table striped padded selectable">
    <tbody>
        <tr>
            <td>First Name</td>
            <td><%=@customer.first_name%></td>
        </tr>
        <tr>
            <td>Last Name</td>
            <td><%=@customer.last_name%></td>
        </tr>
        <tr>
            <td>Email</td>
            <td><%=@customer.email%></td>
        </tr>
        <tr>
            <td>Phone</td>
            <td><%=@customer.phone%></td>
        </tr>
    </tbody>
</table>
<%= link_to 'Edit', edit_customer_path(@customer), class: "ui orange button" %>
<%= link_to 'Delete', @customer, method: :delete, class: "ui red button" %>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
    <% if current_user %>
    <%= link_to 'Customers', customers_path, class: "item" %>
    <%= link_to 'Add Customer', new_customer_path, class: "item" %>
    <% end %>
    <div class="right menu">
        <% if current_user %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "item" %>
        <% else %>
            <%= link_to 'Register', new_user_registration_path, class: "item" %>
            <%= link_to 'Log In', new_user_session_path, class: "item" %>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Customers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>